'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { doc, collection } from 'firebase/firestore';
import { useFirestore, setDocumentNonBlocking, useUser } from '@/firebase';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import type { AIPoweredVocabularyDiscoveryOutput, VocabularyCard } from '@/lib/types';
import { createVocabularyCard } from '@/ai/flows/create-vocabulary-card';
import { generateAudioAction } from '@/app/actions/generateAudioAction';
import { Textarea } from '../ui/textarea';

const formSchema = z.object({
  wordOrPhrase: z.string().min(1, "Word/Phrase is required."),
  partOfSpeech: z.string(),
  translation: z.string(),
  exampleSentence: z.string(),
});

type EditSuggestedCardDialogProps = {
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
  suggestion: AIPoweredVocabularyDiscoveryOutput['suggestedVocabularyCards'][0];
  sessionId: string;
  sessionLanguage: string;
};

export function EditSuggestedCardDialog({ isOpen, setIsOpen, suggestion, sessionId, sessionLanguage }: EditSuggestedCardDialogProps) {
  const firestore = useFirestore();
  const { user } = useUser();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    values: {
      wordOrPhrase: suggestion.wordOrPhrase,
      partOfSpeech: suggestion.partOfSpeech,
      translation: suggestion.translation,
      exampleSentence: suggestion.exampleSentence,
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (!user || !firestore) {
        toast({ variant: 'destructive', title: 'You must be logged in to add a card.' });
        return;
    };
    setIsSubmitting(true);

    try {
      const vocabularyCardsCollection = collection(firestore, `sessions/${sessionId}/vocabularyCards`);
      const newCardRef = doc(vocabularyCardsCollection);
      
      const cardDetails = await createVocabularyCard({
        wordOrPhrase: values.wordOrPhrase,
        motherLanguage: sessionLanguage,
        exampleSentence: values.exampleSentence,
      });

      const audio = await generateAudioAction(values.wordOrPhrase);

      if (audio.error) {
        toast({
          variant: 'destructive',
          title: 'Audio Failed',
          description: `Could not generate audio for "${values.wordOrPhrase}". The card will be added without it.`,
        });
      }

      const finalCardData: Omit<VocabularyCard, 'audioPronunciationUrl'> & { audioPronunciationUrl?: string } = {
        id: newCardRef.id,
        wordOrPhrase: values.wordOrPhrase,
        primaryMeaning: cardDetails.primaryMeaning,
        partOfSpeech: values.partOfSpeech || cardDetails.partOfSpeech,
        pronunciationIpa: cardDetails.pronunciationIpa,
        exampleSentence: values.exampleSentence || cardDetails.exampleSentence,
        translation: values.translation || cardDetails.translation,
        exampleSentenceTranslation: cardDetails.exampleSentenceTranslation,
        creatorId: user.uid,
        creatorName: user.displayName || 'Anonymous',
        creatorPhotoURL: user.photoURL || '',
        createdAt: Date.now(),
        sessionId: sessionId,
      };

      if (audio.media) {
        finalCardData.audioPronunciationUrl = audio.media;
      }

      setDocumentNonBlocking(newCardRef, finalCardData, {});

      toast({
        title: 'Card Added!',
        description: `"${values.wordOrPhrase}" has been added to the session.`,
      });
      setIsOpen(false);
      
    } catch (error) {
      console.error('Failed to create card after edit:', error);
      toast({ variant: 'destructive', title: 'Creation Failed', description: 'Could not create the vocabulary card.' });
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Edit and Add Vocabulary Card</DialogTitle>
          <DialogDescription>
            Review and edit the details before adding to the session. Any empty fields will be auto-generated by AI.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 py-4">
            <FormField
              control={form.control}
              name="wordOrPhrase"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Word or Phrase (Required)</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="partOfSpeech"
                render={({ field }) => (
                    <FormItem>
                    <FormLabel>Part of Speech</FormLabel>
                    <FormControl>
                        <Input {...field} placeholder="e.g., noun, verb..." />
                    </FormControl>
                    <FormMessage />
                    </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="translation"
                render={({ field }) => (
                    <FormItem>
                    <FormLabel>Translation</FormLabel>
                    <FormControl>
                        <Input {...field} />
                    </FormControl>
                    <FormMessage />
                    </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="exampleSentence"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Example Sentence</FormLabel>
                  <FormControl>
                    <Textarea {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="button" variant="ghost" onClick={() => setIsOpen(false)}>Cancel</Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Save and Add to Session
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
